### ISSUE TITLE
It doesn't seem to be possible to configure WithInsecure for an opentelemetry collector endpoint 

### ISSUE THREAD

**Issue by alexb-y42** [jzelinskie/cobrautil#13]

**Comment by jzelinskie** [comment]
This is absolutely true if you only want to use flags. cobrautil also supports the [OpenTelemetry environment variables](https://opentelemetry.io/docs/reference/specification/protocol/exporter/#configuration-options) though, which can configure this.

Because there are just an absolute ton of options as standard environment variables, I'm not sure what ones are best represented as flags or if I should remove the flags entirely and only support the standard environment variables.

**Comment by alexb-y42** [comment]
It doesn't look like OTEL_EXPORTER_OTLP_INSECURE is supported in this component or in opentelemetry-go. At least I can neither make it take any effect nor can I find any code suggesting that it's actually used.

**Comment by jzelinskie** [comment]
hmm I was under the impression from the [otlptrace readme](https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/otlp/otlptrace#configuration) that it was reading environment variables when we call `otlptrace.New()`.

**Comment by vroldanbet** [comment]
As described in https://github.com/jzelinskie/cobrautil/pull/14#issuecomment-1249538572, you can use `OTEL_EXPORTER_OTLP_ENDPOINT`. If the protocol is `http`, the go OTEL library will automatically use insecure communication
